### ISSUE TITLE
seems not working

### ISSUE THREAD

**Issue by Koky999** [SMSAgentSoftware/DeliveryOptimizationMonitor#1]
Hi, 

Found your great tool but it seems not working for me. Tried local computer and also some remote computers, everytime show 0 in all lines. Ran as admin. But on my PC Settings show something different. My build is 20H2.

Any ideas?

Thank you very much!

![Snímek obrazovky (1088)](https://user-images.githubusercontent.com/95216917/144447852-e00d6bd5-9767-4b69-b624-d34b68724321.png)

**Comment by duczz** [comment]
@SMSAgentSoftware i agree, it is not working, but would be nice with a GUI, currently nowhere other exist

**Comment by SMSAgentSoftware** [comment]
Long time coming, but the tool is now working again!
